### ISSUE TITLE
More player animations

### ISSUE THREAD

**Issue by Cheesse** [VenkSociety/More-Models#1]
Through this project it seems that you could implement humanoid models and animations for actions done by the player, such as placing blocks and flying. For example, the server could update the model of a player to a flying model when the player is flying, and it could temporarily update the model of a player to a block change model with the block change animation when the player changes a block.

**Comment by VenkSociety** [comment]
That would require a lot of server-side things and not the ClassicalSharp client. This is only a plugin that adds more models.

**Comment by VenkSociety** [comment]
![sa](https://user-images.githubusercontent.com/19647340/41504228-fbf3581c-722b-11e8-8313-11fa2310a757.png)

This could also potentially be an issue.

**Comment by VenkSociety** [comment]
![sa](https://user-images.githubusercontent.com/19647340/41804977-9da68ee8-76e3-11e8-98ee-b3bc0ab820be.png)
