### ISSUE TITLE
The plugin doesn't load on the new C client

### ISSUE THREAD

**Issue by TheRealPear** [VenkSociety/More-Models#13]
Basically the title. The plugin will not load if you use the new C client but it works as normal on the C# client

**Comment by VenkSociety** [comment]
Rewriting the code in C won't be that hard, but I want to wait until Unknown finishes the C client rewrite before rewriting any code.

**Comment by VenkSociety** [comment]
C releases can be found [here](https://github.com/VenkSociety/More-Models/releases/tag/1.2.2).

**Comment by TheRealPear** [comment]
It gives off error code 000000C1 when loading plugin 'plugins/MoreModels.dll' on launch.

**Comment by UnknownShadow200** [comment]
Most common cause is 32 bit dll with 64 bit client, or vice versa

**Comment by TheRealPear** [comment]
I know this is late, but I got it solved. I was using the correct file (64-bit) for Windows 10 and DirectX x64. The problem was that my file wasn't named `ClassiCube.exe`. I'll just leave this here for the next person in the future that has this problem.
