### ISSUE TITLE
Problems loading and compiling 

### ISSUE THREAD

**Issue by unclassy** [VenkSociety/More-Models#21]
Hi, 
I'm using the 64 dll without problems with windows 10 64 but I didn't manage to make the 32 dll work on windows  10 32. I've got an error while starting classicube.

On the other hand, I'll tried to build the lib from the code with visual studio 2015and 2017 without success.
When referencing the last version I found of classical sharp (0.96) the physics class is missing.
I also tried to reference the last classicube version but I've got an error message that the file is not an assembly component.

Thanks

**Comment by UnknownShadow200** [comment]
Can you include error log/list

**Comment by VenkSociety** [comment]
Are you positive that you were using the 32-bit .dll on your 32-bit machine? I just tested it and it appears to work fine for me. 

As Unknown stated above, if you could please provide the error.log, we could look into the cause of the error. 

As for the `ClassicalSharp` issue, ClassicalSharp is a deprecated version of the ClassiCube client. As such you will need to reference that and not ClassicalSharp.

**Comment by unclassy** [comment]
Hi, 
Yes, I'm positive about the 32 bit dll.

I've checked the client log and it doesn't say anything.

However, while connecting to the server I have the following message on the classicube screen:

Error loading 'plugins/MoreModels.dll'
 Error meaning: The specified module could not be found. (126)
Server software: MCGalaxy 1.9.2.0
![screen](https://user-images.githubusercontent.com/66515270/83974412-701ebe80-a8ed-11ea-9e12-d5432a1ae90a.JPG)

On the server log I've got this when connecting with the 32 bit client
(18:20:54) xxx+ [192.168.1.40] connected using ClassiCube 1.1.6.
and this when connecting with the 64 bit client
(10:33:39) xx+ [192.168.1.15] connected using ClassiCube 1.1.6 + More Models v1.2.4.

As for the visual studio issue, while trying to reference classicube I've got the following error: 
![screen2](https://user-images.githubusercontent.com/66515270/83974528-27b3d080-a8ee-11ea-8906-ebbea55224f3.JPG)

By the way, is there any way on MCGalaxy to execute a batch of commands at once (for example to create a bunch of custom blocks)?

Thanks,

**Comment by Cheesse** [comment]
Is the name of your 32-bit ClassiCube executable "ClassiCube.exe"? If it's named differently the plugin won't be able to load.

**Comment by VenkSociety** [comment]
Is the 32-bit .dll the one from our latest release or did you compile it yourself? What _Cheesse_ said above pretty much sums up that error code. 

As for MCGalaxy, this is unrelated to our project but you can use`/t` or `/static` which basically repeats the previous command until you to `/a` to cancel..

**Comment by unclassy** [comment]
Hi, I'm now able to get the dll you provided working. Indeed I had named the executable ClassiCube32.exe to differentiate it from the 64 one. Thanks a lot!

However, I'm still not able to compile the dll (I'd like to try to create a few new models). I'm always stuck with the reference to classicalsharp/classicube.  Any idea?

Thanks

**Comment by VenkSociety** [comment]
You need to download and compile the [ClassiCube client](https://github.com/UnknownShadow200/ClassiCube) and reference the compiled files.

**Comment by unclassy** [comment]
Hi,
I've re-downloaded the sources of the last client from your link and recompiled it without problems.
Then I tried to reference the compiled ClassCube.exe from the MoreModels solution (add reference/browse...) and I get always the same error: 

![screen](https://user-images.githubusercontent.com/66515270/84113598-2b993d00-aa2b-11ea-9786-4c6463b89ad2.jpg)

Thanks,

**Comment by UnknownShadow200** [comment]
You are trying to load ClassiCube.exe into the old C# more models project, that won't work.

You should use the newer C more models project instead, that is `src/MoreModels.sln`

You then need to right click More Models project -> Properties, then

1) Add an additional include directory that is the directory of the game's source code
![image](https://user-images.githubusercontent.com/6509348/84142045-75b80800-aa97-11ea-8bfb-08c6b805aa50.png)
e.g. `C:/ClassiCube/src`

2) Add an additional library folder that is the directory containing ClassiCube.lib
![image](https://user-images.githubusercontent.com/6509348/84142635-78ffc380-aa98-11ea-83ac-6f6078475bde.png)
e.g. `C:/ClassiCube/src/x64/Debug`

and you should be able to compile now.

**Comment by unclassy** [comment]
Done.
Now I've got the following error:

Error (active)	E0977	a compound literal of type "struct BoxDesc" is not allowed	MoreModels	h:\50_Games\wom\srv_Classic_MCGalaxy\_Resources\Custom Blocks&Models\CustModels\src\Humans\Female.c	6	

Thanks,

**Comment by UnknownShadow200** [comment]
Is it actually preventing you from building the project, or is that 'error' just showing in the error list pane?

e.g. I always see errors about compound literals
![image](https://user-images.githubusercontent.com/6509348/84403181-c02cb680-ac48-11ea-9239-af46ac6be912.png)

but it still builds just fine for me
![image](https://user-images.githubusercontent.com/6509348/84403588-36c9b400-ac49-11ea-9f7c-a996b333fc2d.png)

**Comment by unclassy** [comment]
When I try to compile I have even more errors (7 unresolved externals):
All related to LNK2001 (LNK2001	unresolved external symbol _RTC_CheckStackVars, _RTC_InitBase, _RTC_Shutdown, __GSHandlerCheck, __security_check_cookie, __security_cookie, _DllMainCRTStartup)

I'm sure that there's a problem in the Linker configuration
In my Additional Libraries Directories I have <different options>

When I add the path to ClassiCube.lib is see the path added

![image](https://user-images.githubusercontent.com/66515270/84420350-349c3100-ac1a-11ea-8edc-e345c8ffbcc2.png)

![image](https://user-images.githubusercontent.com/66515270/84420233-074f8300-ac1a-11ea-880a-85d02b212c88.png)

But after I apply the changes, when I come back I don't see it anymore
![image](https://user-images.githubusercontent.com/66515270/84420425-4da4e200-ac1a-11ea-8c22-97a22c327201.png)

**Comment by UnknownShadow200** [comment]
Change configuration to release and then build it
![image](https://user-images.githubusercontent.com/6509348/84446654-541e7280-ac89-11ea-8658-7bf5ddbf3561.png)

**Comment by unclassy** [comment]
That worked!!
Thanks a lot. 
Now fun can start :)

**Comment by unclassy** [comment]
Hi all,
I've developed a few new models as well as some nice skins.
Are you interested for adding them to the project?
Cheers,

**Comment by unclassy** [comment]
A car with siren
![screenshot_20-06-2020-21-07-08](https://user-images.githubusercontent.com/66515270/85210003-cacc0780-b33c-11ea-96de-a3ff4580dca3.png)

**Comment by unclassy** [comment]
A truck
![screenshot_20-06-2020-21-11-08](https://user-images.githubusercontent.com/66515270/85210020-fbac3c80-b33c-11ea-809c-0bfaa133b7e7.png)

**Comment by unclassy** [comment]
A truck with a siren
![screenshot_20-06-2020-21-09-27](https://user-images.githubusercontent.com/66515270/85210031-0d8ddf80-b33d-11ea-8877-97e1964f18a4.png)

**Comment by unclassy** [comment]
A chopper
![screenshot_20-06-2020-21-20-34](https://user-images.githubusercontent.com/66515270/85210042-1c749200-b33d-11ea-9d3d-2c5e58aaa23e.png)

**Comment by Cheesse** [comment]
Sure, just make a pull request.
